In [13]:
import pandas as pd
import re

In [14]:
rooms_csv = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTRvHMQkXQdsW06bzvoOSTw0wkdB4utsbd2JwR2nzASGwkKBhQyDk0_IKu5wl8p5oaambrzr9k3hsMX/pub?gid=279546102&single=true&output=csv",dtype='str')
rooms_csv.head(2)

,OBJECTID,Shape_Area,Unnamed: 2,Layer,Human_readable,Are Room Label and Shape Correct (Yes/No),Problem,Room_label_source
0,5348,61.90560681,NaN,CONFLICT,NaN,NaN,NaN,NaN
1,6145,53.52253626,NaN,CONFLICT,NaN,NaN,NaN,NaN

In [15]:
roman_numerals = {'I':'1','II':'2','III':'3','IV':'4','V':'5','VI':'6','VII':'7','VIII':'8','IX':'9'}
property_ids = []
rooms_layers = []
rooms_labels = []
rooms_ids = []
for row in rooms_csv.iterrows():
    match = re.match(r"^([IVX]+?)([0-9][0-9])([0-9][0-9])(.*?)$",row[1]['Layer'])
    
    if match:
        r = roman_numerals[match.group(1)]
        i = match.group(2).replace("0","")
        p = match.group(3).replace("0","")
        room_label = match.group(4)
        property_ids.append("r{0}-i{1}-p{2}".format(r,i,p))
        rooms_layers.append(row[1]['Layer'])
        rooms_labels.append(room_label)
        rooms_ids.append("room{0}".format(row[1]['OBJECTID']))

rooms_df = pd.DataFrame(data = {"dcterms:identifier":rooms_ids,
                                "p-lod:spatially-within":property_ids,
                                "layer":rooms_layers,
                                "dcterms:title":rooms_labels})

In [18]:
# generate a random sample of 200
pd.set_option('max_rows', 200)
rooms_df.sample(200)

,dcterms:identifier,p-lod:spatially-within,layer,dcterms:title
582,room6990,r1-i7-p19,I0719u,u
739,room7201,r1-i1-p4,I100444,44
7229,room15707,r8-i4-p28,VIII0428n,n
4148,room12605,r6-i14-p37,VI1437b,b
3208,room11665,r6-i8-p21,VI082133,33
1469,room8212,r2-i2-p4,II020407,07
7794,room8740,r9-i2-p1,IX0210i,i
2031,room10441,r5-i3-p8,V030807,07
1817,room10124,r5-i1-p26,V0126t,t
4075,room12532,r6-i14-p2,VI1420m,m
597,room7010,r1-i9-p3,I090301,01
1689,room9996,r5-i1-p4,V010402,02
7923,room8993,r9-i3-p2,IX030209,09
2937,room11394,r6-i7-p6,VI070604,04
1610,room8353,r2-i9-p5,II090503,03
1795,room10102,r5-i1-p23,V0123p,p
7170,room15648,r8-i4-p15,VIII0415c,c
4430,room12887,r6-i16-p26,VI1626P,P
3522,room11979,r6-i9-p7,VI090774,74
4962,room13419,r7-i2-p35,VII0235H,H
4725,room13182,r7-i1-p4,VII014012,12
7840,room8891,r9-i2-p17,IX0217l,l
4263,room12720,r6-i15-p1,VI1501s,s
4468,room12925,r6-i16-p31,VI1631E,E
2567,room11024,r6-i2-p28,VI022815,15
1220,room7840,r1-i14-p11,I141124,24
4478,room12935,r6-i16-p32,VI1632F,F
1102,room7713,r1-i13-p7,I130703,03
2679,room11136,r6-i5-p3,VI050330,30
7701,room8665,r9-i1-p22,IX0122y,y
1950,room10257,r5-i2-p15,V0215m,m
3263,room11720,r6-i9-p1,VI090103,03
755,room7222,r1-i1-p6,I100601,01
7892,room8954,r9-i2-p26,IX0226e,e
1423,room8166,r2-i1-p1,II011002,02
7157,room15635,r8-i4-p12,VIII0412k,k
2547,room11004,r6-i2-p27,VI022701,01
4494,room12951,r6-i16-p36,VI1636C,C
6030,room14507,r7-i9-p5,VII09059011,9011
4358,room12815,r6-i15-p13,VI1513e,e
8533,room9595,r9-i9-p12,IX0912l,l
831,room7327,r1-i11-p3,I110302,02
8329,room9382,r9-i7-p2,IX0720f,f
7124,room15602,r8-i4-p7,VIII0407w,w
7335,room15813,r8-i5-p2,VIII0502u,u
6101,room14578,r7-i11-p2,VII1102-03D,-03D
1216,room7836,r1-i14-p11,I141120,20
5029,room13486,r7-i3-p3,VII0303E,E
7685,room8649,r9-i1-p22,IX0122l,l
796,room7282,r1-i1-p11,I101112,12
1223,room7843,r1-i14-p11,I141127,27
2397,room10854,r6-i2-p1,VI021008,08
4445,room12902,r6-i16-p28,VI1628G,G
3298,room11755,r6-i9-p2,VI090202,02
3646,room12103,r6-i1-p7,VI100712,12
2531,room10988,r6-i2-p25,VI022508,08
5204,room13662,r7-i4-p,VII0400402,402
5657,room14134,r7-i6-p2,VII06029036,9036
304,room6580,r1-i3-p27,I0327c,c
5078,room13536,r7-i3-p1,VII0310C,C
6194,room14671,r7-i12-p7,VII1207E,E
8267,room9299,r9-i6-p8,IX060802,02
6013,room14490,r7-i9-p5,VII09056002,6002
4852,room13309,r7-i2-p16,VII0216Z,Z
6198,room14675,r7-i12-p1,VII1210A,A
5806,room14283,r7-i7-p1,VII07017012CONFLICT,7012CONFLICT
2316,room10773,r6-i1-p1,VI011016,16
773,room7251,r1-i1-p8,I100806,06
5018,room13475,r7-i2-p51,VII0251L,L
3085,room11542,r6-i7-p23,VI072301,01
1751,room10058,r5-i1-p18,V0118h,h
6226,room14703,r7-i12-p14,VII1214B,B
2932,room11389,r6-i7-p3,VI070313,13
5803,room14280,r7-i7-p1,VII07017009,7009
5406,room13883,r7-i4-p4,VII0404302,302
4123,room12580,r6-i14-p33,VI1433o,o
83,room6280,r1-i2-p15,I0215a,a
5211,room13669,r7-i4-p,VII0400604,604
7865,room8916,r9-i2-p21,IX0221i,i
7955,room9033,r9-i3-p5,IX030528,28
8321,room9374,r9-i7-p19,IX0719l,l
2036,room10446,r5-i3-p8,V030812,12
1472,room8215,r2-i2-p4,II020410,10
6072,room14549,r7-i1-p3,VII1003-14S',-14S'
1301,room7921,r1-i16-p5,I160508,08
4267,room12724,r6-i15-p1,VI1501w,w
7285,room15763,r8-i4-p46,VIII044603,03
1325,room7945,r1-i17-p2,I170207,07
4780,room13237,r7-i2-p3,VII0203K,K
2304,room10761,r6-i1-p1,VI011006d,06d
3341,room11798,r6-i9-p2,VI090243,43
2435,room10892,r6-i2-p14,VI021408,08
6797,room15275,r8-i2-p28,VIII0228s,s
6321,room14798,r7-i13-p7,VII1307-04,-04
2011,room10421,r5-i3-p6,V0306b,b
2451,room10908,r6-i2-p16,VI021618,18
8652,room9746,r9-i14-p4,IX140443,43
5965,room14442,r7-i9-p3,VII09038005,8005
1101,room7712,r1-i13-p7,I130702,02
2256,room10713,r6-i1-p7,VI010715,15
4782,room13239,r7-i2-p3,VII0203M,M
8193,room9226,r9-i5-p16,IX0516e',e'
7472,room15950,r8-i5-p39,VIII0539e,e
4245,room12702,r6-i15-p1,VI150104,04
3169,room11626,r6-i8-p15,VI081502,02
3812,room12269,r6-i11-p1,VI111043,43
7804,room8750,r9-i2-p12,IX0212d,d
8126,roomnan,r9-i5-p8,IX0508c,c
4760,room13217,r7-i1-p51,VII0151A,A
1335,room7955,r1-i17-p4,I170406,06
809,room7300,r1-i1-p18,I101803,03
8339,room9392,r9-i7-p2,IX0720q,q
3454,room11911,r6-i9-p6,VI090645,45
1496,room8239,r2-i3-p3,II030315,15
6908,room15386,r8-i3-p4,VIII030409,09
6863,room15341,r8-i2-p36,VIII0236i,i
4507,room12964,r6-i16-p38,VI1638J,J
7757,room8703,r9-i2-p4,IX0204c,c
6080,room14557,r7-i1-p5,VII1005-08-13F,-08-13F
4834,room13291,r7-i2-p16,VII0216G,G
87,room6293,r1-i2-p15,I0215e,e
4283,room12740,r6-i15-p2,VI1502p,p
6037,room14514,r7-i9-p5,VII09059018,9018
5086,room13544,r7-i3-p11,VII0311-12G,-12G
3755,room12212,r6-i11-p4,VI110411,11
2868,room11325,r6-i6-p2,VI060201,01
1117,room7733,r1-i13-p8,I130807,07
6809,room15287,r8-i2-p29,VIII0229b',b'
1624,room8368,r3-i2-p1,III0201n,n
484,room6849,r1-i7-p2,I0702b,b
4836,room13293,r7-i2-p16,VII0216I,I
6384,room14861,r7-i14-p5,VII1405-17-18-19-21,-17-18-19-21
7089,room15567,r8-i4-p1,VIII0401d,d
8621,room9715,r9-i14-p4,IX140407,07
617,room7037,r1-i9-p5,I090510,10
7726,room8680,r9-i1-p22,IX0122d',d'
5451,room13928,r7-i4-p5,VII040570O,70O
3943,room12400,r6-i13-p6,VI130608,08
984,room7541,r1-i12-p6,I120610,10
2635,room11092,r6-i3-p19,VI031901,01
1346,room7966,r1-i2-p4,I200406,06
3474,room11931,r6-i9-p6,VI090660,60
939,room7483,r1-i11-p17,I111707,07
3492,room11949,r6-i9-p6,VI0906B,B
3023,room11480,r6-i7-p18,VI071814,14
5480,room13957,r7-i4-p6,VII0406301,301
1293,room7913,r1-i16-p4,I160411,11
986,room7544,r1-i12-p6,I120612,12
7266,room15744,r8-i4-p39,VIII043903,03
482,room6847,r1-i7-p2,I0702a,a
5712,room14189,r7-i7-p,VII07002(l),2(l)
7798,room8744,r9-i2-p1,IX0210n,n
6686,room15164,r8-i2-p14,VIII0214m,m
4696,room13153,r7-i1-p36,VII0136F,F
115,room6322,r1-i2-p18,I0218c,c
8167,roomnan,r9-i5-p12,IX0512a,a
5285,room13743,r7-i4-p2,VII0402407,407
4626,room13083,r7-i1-p14,VII01141A,1A
6157,room14634,r7-i11-p11,VII1111-14R,-14R
3295,room11752,r6-i9-p2,VI090201,01
4830,room13287,r7-i2-p16,VII0216C,C
2165,room10621,r5-i5-p3,V0503e,e
171,room6411,r1-i3-p3,I0303g,g
3957,room12414,r6-i13-p6,VI130622,22
5302,room13760,r7-i4-p2,VII0402608,608
4692,room13149,r7-i1-p36,VII0136A,A
3550,room12007,r6-i1-p2,VI100203,03
2644,room11101,r6-i3-p21,VI032106,06
2537,room10994,r6-i2-p26,VI022602,02
7348,room15826,r8-i5-p9,VIII050905,05
6467,room14944,r7-i15-p,VII15001(v),1(v)
7956,room9034,r9-i3-p5,IX030529,29
3502,room11959,r6-i9-p7,VI090754,54
4986,room13443,r7-i2-p45,VII0245G,G
465,room6826,r1-i7-p1,I070102,02
1963,room10270,r5-i2-p15,V0215x,x
1695,room10002,r5-i1-p7,V010702,02
5672,room14149,r7-i6-p2,VII06029051,9051
5951,room14428,r7-i9-p3,VII09032001,2001
3607,room12064,r6-i1-p6,VI100618,18
6230,room14707,r7-i12-p14,VII1214F,F
2836,room11293,r6-i6-p1,VI060103A,03A
3862,room12319,r6-i12-p2,VI120212,12
3849,room12306,r6-i11-p19,VI111911,11
3093,room11550,r6-i7-p23,VI072309,09
6900,room15378,r8-i3-p3,VIII030301,01
2005,room10415,r5-i3-p4,V0304R,R
1677,room9984,r5-i1-p3,V010301,01
449,room6805,r1-i4-p25,I042552,52
5966,room14443,r7-i9-p3,VII09038006,8006
3435,room11892,r6-i9-p6,VI090637,37
1197,room7816,r1-i14-p11,I141101,01
839,room7338,r1-i11-p5,I110506,06
7446,room15924,r8-i5-p34,VIII053401,01
2678,room11135,r6-i5-p3,VI050329,29
2526,room10983,r6-i2-p25,VI022503,03
1395,room8138,r2-i1-p2,II010206,06
6167,room14644,r7-i11-p13,VII1113C,C
1737,room10044,r5-i1-p15,V0115e,e
7821,room8765,r9-i2-p16,IX0216l,l